### ISSUE TITLE
Boomerang crashes game, leaves it in none responsive but still bakground flowing mode 

### ISSUE THREAD

**Issue by Ahrio76** [jangler/oracles-randomizer#161] opened 2023-10-22 21:27 UTC
Spolier for locations:

sphere 5:
cave north of D1             <- (magic) boomerang

sphere 6:
black beast's chest          <- (magic) boomerang

**Comment by jangler** [comment] 2023-10-22 22:26
Sounds like a duplicate of #159.

**Closed by jangler** 2023-10-22 22:26 UTC
